export const sharedStyles = {
  btnPrimary: {
    background: "linear-gradient(135deg, #00ffc8, #00b894)",
    color: "#0a0a0f",
    border: "none",
    borderRadius: 30,
    padding: "14px 32px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    marginRight: 16,
    transition: "transform 0.2s, box-shadow 0.2s",
    boxShadow: "0 0 20px rgba(0,255,200,0.3)",
  },
  btnSecondary: {
    background: "transparent",
    color: "#00ffc8",
    border: "1.5px solid rgba(0,255,200,0.4)",
    borderRadius: 30,
    padding: "13px 32px",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  section: {
    padding: "100px 8%",
  },
  sectionTag: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 3,
    color: "#00ffc8",
    textTransform: "uppercase" as const,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: "clamp(28px, 4vw, 42px)",
    fontFamily: "'Playfair Display', serif",
    fontWeight: 700,
    marginBottom: 16,
    color: "#f1f5f9",
  },
  divider: {
    width: 48,
    height: 3,
    background: "linear-gradient(90deg, #00ffc8, transparent)",
    borderRadius: 2,
    marginBottom: 48,
  },
};
